Add item requests
AlexanderKolnakov/java-shareit pull request #3
Opened 2023-02-12 10:54 UTC by AlexanderKolnakov

2023-02-21 19:50 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void createBooking_whenBookingRequestValid_thenReturnBooking() {
Если есть желание, попробуй сделать параметризованные тесты https://www.baeldung.com/parameterized-tests-junit-5
Это позволит сократить количество кода, но при этом покрытие не уменьшится

2023-02-21 19:54 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>      }
На 78-й строчке используется deprecated функция, что ок сейчас, но в настоящих проектах лучше не делать.

2023-02-21 20:01 UTC, EvgenyKoptubenko commented
В BookingServiceImpl есть такая функция
private void checkMayUserGetBookingInfo(Long userId, Long bookingId) {
        if (!(bookingRepository.getById(bookingId).getItem().getOwner().equals(userId)
                || bookingRepository.getById(bookingId).getBooker().getId().equals(userId))) {
            throw new EntityNotFoundException("Пользователь с id " + userId + " не может получить информацию " +
                    "о бронировании с id  " + bookingId + " так как не является ее владельцем или арендатором");
        }
    }
Тут два раза идет обращение к базе данных за одним и тем же 
bookingRepository.getById(bookingId)

Если есть желание, попробуй убрать в коде дублирование запросов к базе данных.

2023-02-21 20:03 UTC, EvgenyKoptubenko commented
Когда добавляешь пользователя второй раз, то приходит отличное сообщение об ошибке
Пользователь с email232фы322ц222ы2@email.com уже зарегистрирован.
Но при этом код ошибки 500.
Все-таки это не ошибка на стороне сервера. Это скорее Conflict ну или Bad Request

2023-02-21 20:04 UTC, EvgenyKoptubenko commented
Не работает Patch для пользователя

curl --request PATCH \
  --url http://localhost:8080/users/1 \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameIуddуtem",
	"email":"wrong_emai@lmail.com",
  "login":"logiddуxcыцn222s",
	"birthday":"2012-24-23T18:25:43.511Z"
}'

Попробуй отправить обновление пользователя один раз, потом поменять логин и отправить еще раз.
Сервер пришлет ошибку Пользователь с wrong_emai@lmail.com уже зарегистрирован.

2023-02-21 20:05 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Есть немного предложений по улучшению приложения

2023-02-24 13:21 UTC, AlexanderKolnakov commented
Параметризованные тесты постараюсь успеть сделать к сдаче 16ого спринта. Уже сталкивался с ними

2023-02-24 19:54 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-25 12:13 UTC, merged